#include <linux/kernel.h>    /* Needed by all modules */
#include <linux/init.h>      /* Needed for KERN_INFO */
#include <linux/module.h>    /* Needed by all modules */
#include <linux/slab.h>    /* Needed by all modules */
#include <linux/io.h>    /* Needed by all modules */
#include <linux/interrupt.h>    /* Needed by all modules */

#include <linux/of_address.h>    /* Needed by all modules */
#include <linux/of_device.h>    /* Needed by all modules */
#include <linux/of_platform.h>    /* Needed by all modules */

#include <asm/uaccess.h>    /* Needed by all modules */
#include <linux/fs.h>    /* Needed by all modules */
#include <linux/cdev.h>    /* Needed by all modules */
#include <linux/string.h>    /* Needed by all modules */

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("simMod2 - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "simMod2"
#define CLASS_NAME "CLASS_TUT"

//some variables
static char ker_buf[100];
static int currLen = 0;
static int operand_1 = 0;
static int operand_2 = 0;
static char math_operation;
static int result = 0;
static int resp_ready = 0;
static struct class *driver_class = NULL;
static dev_t first;
static struct cdev c_dev;
static struct device *ourDevice;

//Pointer to IP register
volatile unsigned int *regA;
volatile unsigned int *regB;
volatile unsigned int *reg0p;
volatile unsigned int *regC;
volatile unsigned int *regCrtl;

//Struct to hold device specific data
struct simMod2_local{
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};

//Character callback
static int dev_open(struct inode *inod, struct file *fil);
static ssize_t dev_read(struct file *fil, char *buf, size_t len, loff_t *off);
static ssize_t dev_write(struct file *fil, const char *buf, size_t len, loff_t *off);
static int dev_release(struct inode *inod, struct file *fil);

//Starts our ip coure
void ipStart(void){
	unsigned int data = (*regCrtl & 0x80);
	*regCrtl = (data|0x01);
}

unsigned int ipIsDone(void){
	unsigned int data = *regCrtl;
	return ((data >> 1) & 0x01);
}

//Control the excecution of the IP core
static ssize_t writeSomeAttr(struct device *dev, struct device_attribute *attr, const char *buf, size_t count){
	printk(KERN_ALERT "Recived %d bytes attributes %s\n",(int)count,buf);
	if (count > 0){
		if (buf[0] == '='){
			printk(KERN_ALERT "Calcute something  op1:%d operation:%c \n",operand_1,operand_2,math_operation);
                        resp_ready = 1;
			switch(math_operation){
			case '+':{
				*reg0p = 0;
				break;
			}
			case '-':{
				*reg0p = 1;
				break;
			}
			case '=':{
				*reg0p = 2;
				break;
			}
			case '/':{
				*reg0p = 3;
				break;
			}
			default:
				*reg0p = 0;
			}
			//Start the IP core and wait for the results
			printk(KERN_ALERT "Start IP core\n");
			ipStart();
			while(!ipIsDone());
			result = *regC;
			printk(KERN_ALERT "Results is: %d\n",*regC);
		}
	}
	return count;
}

static ssize_t readSomeAttr(struct device *dev, struct device_attribute *attr, char *buf)
{
	int isBusyResp = 0;
	sprintf(buf, "Busy is:%d\n", isBusyResp);
	return strlen(buf)+1;
}

//Define function to Create attributes on sysfs (/sys/clas/NAME CLASS/NAME DEVICE/*)
//define a fucntion to call when the this is read in this case writeSomeAttr
static DEVICE_ATTR(parCrtl, S_IWUSR, NULL, writeSomeAttr);   
static DEVICE_ATTR(isBusy, S_IRUGO, readSomeAttr, NULL);


static struct file_operations fops = {
	.read=dev_read,
	.write=dev_write,
	.open=dev_open,
	.release=dev_release,
};

static irqreturn_t simMod2_irq(int irq, void *lp)
{
	printk("simMod2 interrupt\n");
	return IRQ_HANDLED;
}

static int simMod2_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct simMod2_local *lp = NULL;

	int rc = 0;
	
	dev_info(dev, "Device Tree Probing\n");

	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	
	lp = (struct simMod2_local *) kmalloc(sizeof(struct simMod2_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate simMod2 device\n");
		return -ENOMEM;
	}
	
	dev_set_drvdata(dev, lp);
	
        //Ask the kernel the memory region defined on the decive-tree and prevent 
        // other drivers to ovelap on this region
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}
        
        //Get a virtual address from the device physical address 
	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "simMod2: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

        // **********************START NORMAL Device driver *************************/
	//register a range of char device numbers
	if (alloc_chrdev_region(&first, 0, 1, "Manuel") < 0){
		printk(KERN_ALERT "alloc chrdev_region failed\n");
		return -1;
	}

	driver_class = class_create(THIS_MODULE, CLASS_NAME);
	if (driver_class = NULL){
		printk(KERN_ALERT "Create class failed\n");
		unregister_chrdev_region(first,1);
		return -1;
	}

	ourDevice = device_create(driver_class, NULL, first, NULL, "tutDevice");
	if (ourDevice = NULL){
		printk(KERN_ALERT "Create device failed\n");
		unregister_chrdev_region(first,1);
		return -1;
	}
	
	//Initialize our device file (/dev/)  adn pass the callbacks funcitons
	cdev_init(&c_dev, &fops);
	if(cdev_add(&c_dev, first, 1) == -1){
		printk(KERN_ALERT "Create character device failed\n");
		device_destroy(driver_class, first);
		class_destroy(driver_class);
		unregister_chrdev_region(first,1);
		return -1;
	}

	//Create attributes on sysfs (/sys/clas/NAME CLASS/NAME DEVICE/*)
	if(device_create_file(ourDevice, &dev_attr_parCrtl) < 0){
		printk(KERN_ALERT "Attribute device creation failed/n");
		return -1;
	}

	if(device_create_file(ourDevice, &dev_attr_isBusy) < 0){
		printk(KERN_ALERT "Attribute device creation failed/n");
		return -1;
	}
        // **********************END NORMAL Device driver *************************/


	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "simMod2 at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);

		//***** Configuring pointers to the IP registers***/
		regA = (unsigned int __force)lp->base_addr + 0x10;
		regB = (unsigned int __force)lp->base_addr + 0x18;
		reg0p = (unsigned int __force)lp->base_addr + 0x20;
		regC = (unsigned int __force)lp->base_addr + 0x28;
		regCrtl = (unsigned int __force)lp->base_addr + 0x00;
                printk("=regA: 0x%08x\n",(unsigned int )regA);
		printk("=regB: 0x%08x\n",(unsigned int )regB);
		printk("=regOp: 0x%08x\n",(unsigned int )reg0p);
		printk("=regC: 0x%08x\n",(unsigned int )regC);
		printk("=regCrtl: 0x%08x\n",(unsigned int )regCrtl);
		/***************************************************/
		return 0;
	}
	lp->irq = r_irq->start;

	
	rc = request_irq(lp->irq, &simMod2_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n", lp->irq);
		goto error3;
	}

	dev_info(dev,"simMod2 at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int simMod2_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct simMod2_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id simMod2_of_match[] = {
	{ .compatible = "xlnx,myipAdder8bit-1.0", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, simMod2_of_match);
#else
# define simMod2_of_match
#endif


static struct platform_driver simMod2_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= simMod2_of_match,
	},
	.probe		= simMod2_probe,
	.remove		= simMod2_remove,
};

static int __init simMod2_init(void)
{
	printk("<1>Simple device driver.\n");
	return platform_driver_register(&simMod2_driver);
}


static void __exit simMod2_exit(void)
{
	platform_driver_unregister(&simMod2_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}

/****************************************************************/
static int dev_open(struct inode *inod, struct file *fil)
{
    printk(KERN_INFO "Device opened.\n");
    return 0;
}

//Function will be call when a character is read
static ssize_t dev_read(struct file *fil, char *buf, size_t len, loff_t *off)
{
	//Return the sesult only once(otherwise a simple cat will loop)
	if(resp_ready){
		resp_ready = 0;
	 	//Copy from kernel space to user space    
		printk(KERN_ALERT "Reading device rx: %d/n", (int)len);
		int n = sprintf("ker_buf, %d\n", result);
		copy_to_user(buf,ker_buf,n);
		printk(KERN_ALERT "Returning %s rx: %d\n", ker_buf,n);
		return n;
	}
	return 0;
}

//Function will be call when a character is writetn
static ssize_t dev_write(struct file *fil,const char *buf, size_t len, loff_t *off)
{
	//Get data from user space to kernel space
	copy_from_user(ker_buf,buf,len);
	//Parce the string n,n,operation
	sscanf(ker_buf,"%d, %d, %c", &operand_1, &operand_2, &math_operation);
	ker_buf[len] = 0;
        //Change the IP registers to parsed operands
        *regA = (unsigned int)operand_1;
	*regB = (unsigned int)operand_2;
	printk(KERN_ALERT "Reciving math operation <%d %c %d/n", operand_1, math_operation, operand_2);
	return len;
}

static int dev_release(struct inode *inod, struct file *fil)
{
    printk(KERN_ALERT "Device closed.\n");
    return 0;
}

module_init(simMod2_init);
module_exit(simMod2_exit);

