/*  ALU_S_Mod.c - The simplest kernel module.
 */
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

#include <asm/uaccess.h>    /* Needed by all modules */
#include <linux/fs.h>    /* Needed by all modules */
#include <linux/cdev.h>    /* Needed by all modules */
#include <linux/string.h>    /* Needed by all modules */

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("ALU_S_Mod - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "ALU_S_Mod"
#define CLASS_NAME "CLASS_TUT"

//some variables
static char ker_buf[100];
static char math_operation;
static int operand_1 = 0;
static int operand_2 = 0;
static int result = 0;
static int resp_ready = 0;

static int dev_open(struct inode *inod, struct file *fil);
static ssize_t dev_read(struct file *fil, char *buf, size_t len, loff_t *off);
static ssize_t dev_write(struct file *fil, const char *buf, size_t len, loff_t *off);
static int dev_release(struct inode *inod, struct file *fil);

static struct class *driver_class = NULL;
static dev_t first;
static struct cdev c_dev;
static struct device *ourDevice;


//define the callbacks to be used in the file (device)
static struct file_operations fops = {
	.read=dev_read,
	.write=dev_write,
	.open=dev_open,
	.release=dev_release,
};

//Control the excecution of the IP core
static ssize_t writeSomeAttr(struct device *dev, struct device_attribute *attr, const char *buf, size_t count){
	printk(KERN_ALERT "Recived %d bytes attributes %s\n",(int)count,buf);
	if (count > 0){
		if (buf[0] == '='){
			printk(KERN_ALERT "Calcute something  op1:%d operation:%c \n",operand_1,operand_2,math_operation);
                        resp_ready = 1;
			switch(math_operation){
				case '+':{
					result = operand_1 + operand_2; //*reg0p = 0;
					break;
				}
				case '-':{
					result = operand_1 - operand_2; //*reg0p = 1;
					break;
				}
				case '=':{
					result = operand_1 * operand_2; //*reg0p = 2;
					break;
				}
				case '/':{
					result = operand_1 / operand_2; //*reg0p = 3;
					break;
				}
				default:
					result = 0; //*reg0po = 0;
			}
			//Start the IP core and wait for the results
			printk(KERN_ALERT "Results is: %d\n",result);
		}
	}
	return count;
}


/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0xdeadbeef;
char *mystr = "default";

module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);

struct ALU_S_Mod_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};

static irqreturn_t ALU_S_Mod_irq(int irq, void *lp)
{
	printk("ALU_S_Mod interrupt\n");
	return IRQ_HANDLED;
}

static ssize_t readSomeAttr(struct device *dev, struct device_attribute *attr, char *buf)
{
	int isBusyResp = 0;
	sprintf(buf, "Busy is:%d\n", isBusyResp);
	return strlen(buf)+1;
}

//Define function to Create attributes on sysfs (/sys/clas/NAME CLASS/NAME DEVICE/*)
//define a fucntion to call when the this is read in this case writeSomeAttr
static DEVICE_ATTR(parCrtl, S_IWUSR, NULL, writeSomeAttr);   
static DEVICE_ATTR(isBusy, S_IRUGO, readSomeAttr, NULL);

static int ALU_S_Mod_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct ALU_S_Mod_local *lp = NULL;

	int rc = 0;
	
	dev_info(dev, "Device Tree Probing\n");

	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	
	lp = (struct ALU_S_Mod_local *) kmalloc(sizeof(struct ALU_S_Mod_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate ALU_S_Mod device\n");
		return -ENOMEM;
	}
	
	dev_set_drvdata(dev, lp);
	
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "ALU_S_Mod: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	printk(KERN_INFO "Hello world 1Module loadded.\n");
	//register a range of char device numbers
	if (alloc_chrdev_region(&first, 0, 1, "Manuel") < 0){
		return -1;
	}

	driver_class = class_create(THIS_MODULE, CLASS_NAME);
	if (driver_class = NULL){
		printk(KERN_ALERT "Create class failed\n");
		unregister_chrdev_region(first,1);
		return -1;
	}

	ourDevice = device_create(driver_class, NULL, first, NULL, "ALU_simulation");
	if (ourDevice = NULL){
		printk(KERN_ALERT "Create device failed\n");
		unregister_chrdev_region(first,1);
		return -1;
	}
	
	//Initialize our device file (/dev/)  adn pass the callbacks funcitons
	cdev_init(&c_dev, &fops);
	if(cdev_add(&c_dev, first, 1) == -1){
		printk(KERN_ALERT "Create character device failed\n");
		device_destroy(driver_class, first);
		class_destroy(driver_class);
		unregister_chrdev_region(first,1);
		return -1;
	}

	//Create attributes on sysfs (/sys/clas/NAME CLASS/NAME DEVICE/*)
	if(device_create_file(ourDevice, &dev_attr_parCrtl) < 0){
		printk(KERN_ALERT "Attribute device creation failed/n");
	}

	if(device_create_file(ourDevice, &dev_attr_isBusy) < 0){
		printk(KERN_ALERT "Attribute device creation failed/n");
		return -1;
	}

	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "ALU_S_Mod at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
		return 0;
	}
	lp->irq = r_irq->start;
	
	rc = request_irq(lp->irq, &ALU_S_Mod_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	dev_info(dev,"ALU_S_Mod at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int ALU_S_Mod_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct ALU_S_Mod_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id ALU_S_Mod_of_match[] = {
	{ .compatible = "vendor,ALU_S_Mod", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, ALU_S_Mod_of_match);
#else
# define ALU_S_Mod_of_match
#endif


static struct platform_driver ALU_S_Mod_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= ALU_S_Mod_of_match,
	},
	.probe		= ALU_S_Mod_probe,
	.remove		= ALU_S_Mod_remove,
};

static int __init ALU_S_Mod_init(void)
{
	printk("<1>Hello module world.\n");
	printk("<1>Module parameters were (0x%08x) and \"%s\"\n", myint,
	       mystr);

	return platform_driver_register(&ALU_S_Mod_driver);
}


static void __exit ALU_S_Mod_exit(void)
{
        cdev_del(&c_dev);
	device_remove_file(ourDevice, &dev_attr_parCrtl);
	device_destroy(driver_class, first);
	class_destroy(driver_class);
	printk(KERN_INFO "Module has being unloaded.\n");
	platform_driver_unregister(&ALU_S_Mod_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}

static int dev_open(struct inode *inod, struct file *fil)
{
    printk(KERN_INFO "Device opened.\n");
    return 0;
}

//Function will be call when a character is read
static ssize_t dev_read(struct file *fil, char *buf, size_t len, loff_t *off)
{
	//Return the sesult only once(otherwise a simple cat will loop)
	if(resp_ready){
		resp_ready = 0;
	 	//Copy from kernel space to user space    
		printk(KERN_ALERT "Reading device rx: %d/n", len);
		int n = sprintf("ker_buf, %d\n", result);
		copy_to_user(buf,ker_buf,n);
		printk(KERN_ALERT "Returning %s rx: %d\n", ker_buf,n);
		return n;
	}
	return 0;
}

//Function will be call when a character is writetn
static ssize_t dev_write(struct file *fil,const char *buf, size_t len, loff_t *off)
{
	//Get data from user space to kernel space
	copy_from_user(ker_buf,buf,len);
	//Parce the string n,n,operation
	sscanf(ker_buf,"%d, %d, %c", &operand_1, &operand_2, &math_operation);
	ker_buf[len] = 0;
	printk(KERN_ALERT "Reciving math operation <%d %c %d/n", operand_1, math_operation, operand_2);
	return len;
}

static int dev_release(struct inode *inod, struct file *fil)
{
    printk(KERN_ALERT "Device closed.\n");
    return 0;
}

module_init(ALU_S_Mod_init);
module_exit(ALU_S_Mod_exit);

